## Pandas
- Series : 단일 데이터 열과 인덱스(index)로 구성된 1차원 구조체
- DataFrame : 행 인덱스와 열 이름(Columns)을 가진 2차원 표 구조체

In [3]:
import pandas as pd

scores = pd.Series([90,85,88])

print(scores)

0    90
1    85
2    88
dtype: int64

In [9]:
data = {
    '이름':['김철수','이영희','박지민'],
    '부서':['개발','기획','개발'],
    '급여':[4500,5200,4800]
}
df = pd.DataFrame(data)

df.info() # index와 컬럼 목록, 널이 아닌 데이터 수, 데이터 타입등 데이터 프레임의 요약 Non-Null Count는 널 찾는데도 쓴다
df.describe() # 데이터의 기초 통계, 평균, 최소값, 최고값 등을 보여준다

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   부서      3 non-null      str
 2   급여      3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

                급여
count     3.000000
mean   4833.333333
std     351.188458
min    4500.000000
25%    4650.000000
50%    4800.000000
75%    5000.000000
max    5200.000000

In [ ]:
# 열 추가 및 수정
df['보너스'] = df['급여'] *0.1 #급여에 0.1 배를 한 값들로 보너스 컬럼을 추가한

print(df)

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박지민  개발  4800  480.0

### loc 와 iloc
- loc : 행의 이름으로 검색
    - loc[행 라벨]
    - loc[행 라벨, 컬럼 이름]
    - loc[시작행:종료행, [컬럼1,컬럼2,...]]
    - loc[..., 시작컬럼:종료컬럼]

- iloc : 숫자 인덱스로 검색
    - loc와 사용 방법은 동일하지만 행 라벨을 인덱스로 변경

In [13]:
df = pd.DataFrame({
    '나이': [25,30,35,40],
    '점수': [80,95,70,85],
    '등급': ['B','A','C','B']
}, index = ['user1','user2','user3','user4'])

df

       나이  점수 등급
user1  25  80  B
user2  30  95  A
user3  35  70  C
user4  40  85  B

In [ ]:
df.loc['user1'], type(df.loc['user1']) # user1 의 로우 데이터 출력

(나이    25
 점수    80
 등급     B
 Name: user1, dtype: object,
 pandas.Series)

In [17]:
df.loc['user1':'user2', ['점수','등급']] # 행 부분은 []로 감싸지 않는다 : 를 썻기 때문
df.loc['user1':'user2','점수':'등급'] # 열에도 : 쓰면 마찬가지

       점수 등급
user1  80  B
user2  95  A

In [ ]:
(df['나이'] >= 30) & (df['점수']>=80) # 각 index에서 조건에 해당하는 true, false를 반환한다
df[(df['나이'] >= 30) & (df['점수']>=80)] # df[] 로 위 조건에 맞는 데이터를 반환한다

       나이  점수 등급
user2  30  95  A
user4  40  85  B

In [ ]:
df.query('나이 >= 30 and 점수 >= 80') # query 필터링을 사용해서 할 수 있다

       나이  점수 등급
user2  30  95  A
user4  40  85  B

### 결측치 탐지 및 처리
- info()
- isna(),isnull() : 같은 기능으로 차이가 없다 isna() 를 많이 쓴다

In [21]:
import numpy as np

# 결측치 - np.nan, pd.NA, NONE

raw_df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [pd.NA, 5, 6], 'C': [7, 8, 9]})

raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      object
 2   C       3 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [ ]:
True + True #파이썬에서 True 는 1 False 는 0으로 숫자 사칙 연산에도 이용할 수 있다

2

In [ ]:
raw_df.isna() # 결측치(null) 이면 true를 반환한다

       A      B      C
0  False   True  False
1   True  False  False
2  False  False  False

In [ ]:
raw_df.isna().sum() # true false를 다 더한다 true는 1이므로 각 컬럼에서 결측치의 개수를 알 수 있다

A    1
B    1
C    0
dtype: int64

In [29]:
raw_df.dropna() # 결측치가 있는 행을 삭제한다

     A  B  C
2  3.0  6  9

In [ ]:
raw_df.dropna(axis=1) # 결측치가 있는 열을 삭제한다 (기본은 0 이므로 위에서는 입력하지 않는다)

   C
0  7
1  8
2  9

In [36]:
df_age = pd.DataFrame({'나이': [20, 25, None, 30, 95]})

median_val = df_age['나이'].median()   # 나이 열의 중앙값을 변수에 저장한다
print('중앙값:',median_val)
#df_age['나이'] = df_age['나이'].fillna(median_val) # 비어있는(None)에 중앙값을 입력한다

중앙값: 27.5

In [37]:
#df_age.ffill() # 앞에 있는 값으로 채운다
df_age.bfill() # 뒤에 있는 값으로 채운다

     나이
0  20.0
1  25.0
2  30.0
3  30.0
4  95.0